sudo: required

language: ruby
cache: bundler

env:
  global:
    - RAILS_ENV=test
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

services:
  - docker

before_install:
  - echo 'GO!'

script:
  - bundle exec rake db:create db:migrate
  - bundle exec rspec

  - gem i codeclimate-test-reporter 
  - CODECLIMATE_REPO_TOKEN=$CC_TEST_REPORTER_ID codeclimate-test-reporter

  - if [ "$TRAVIS_TAG" != "" ]; then
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD ;
      docker pull udalov/youtube-fetcher ;
      docker build -t udalov/youtube-fetcher:$TRAVIS_TAG . ;
      docker push udalov/youtube-fetcher:$TRAVIS_TAG ;
    fi

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD ;
      docker pull udalov/youtube-fetcher ;
      docker build -t udalov/youtube-fetcher:latest . ;
      docker push udalov/youtube-fetcher:latest ;
      eval $DEPLOY_CMD ;
    fi
